version: "3.9"
services:
  frontend:
    build: 
      context: ./h4221-frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200    
    volumes:
      - ./h4221-frontend:/dockerfront
    depends_on:
      - backend
    networks:
      - my-network
    container_name: frontend
    command: ng serve --host 0.0.0.0 --disable-host-check --poll 2000
  backend:
    build: 
      context: ./h4221-backend
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./h4221-backend:/dockerback
    depends_on:
      - mongo
    networks:
      - my-network
    container_name: backend
    command: mvn spring-boot:run
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pld-smart-database
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    driver: local
networks:
  my-network:
# volumes:
#   - datamongodb:/data/db